name: Verify Tests

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  verify-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Run package installation
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test
